config/routes.rb
Rails.application.routes.draw do
  resources :marks
  resources :exams
  resources :courses
  resources :subjects
  resources :grades
  resource :session
  resources :users do
    collection do
      get :students
    end
  end
  resources :passwords, param: :token
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "pages#landing"
  get "dashboard", to: "pages#dashboard"

  namespace :admin do
    root "dashboard"
    resources :users
  end

  namespace :teacher do
    root "dashboard"
  end

  namespace :student do
    root "dashboard"
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/course.rb
class Course < ApplicationRecord
  belongs_to :grade
  belongs_to :subject
  belongs_to :teacher, class_name: "User"
  has_many :exams
  has_many :marks

  scope :by_grade, ->(grade_id) {
    where(grade_id: grade_id) if grade_id.present?
  }

  scope :by_subject, ->(subject_id) {
    where(subject_id: subject_id) if subject_id.present?
  }

  def display_name
    "#{grade.name} - #{subject.name}"
  end
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :session
  delegate :user, to: :session, allow_nil: true
end

app/models/exam.rb
class Exam < ApplicationRecord
  belongs_to :course
  has_many :marks

  scope :by_grade, ->(grade_id) {
    joins(course: :grade)
    .where(grades: {id: grade_id}) if grade_id.present?
  }

  scope :by_subject, ->(subject_id) {
    joins(course: :subject)
    .where(subjects: {id: subject_id}) if subject_id.present?
  }

  def display_name
    "#{course.display_name} - #{self.title}"
  end
end

app/models/grade.rb
class Grade < ApplicationRecord
  has_many :users, dependent: :restrict_with_exception
  has_many :courses, dependent: :restrict_with_exception
end

app/models/mark.rb
class Mark < ApplicationRecord
  belongs_to :course
  belongs_to :exam, optional: true
  belongs_to :student, class_name: "User"
  
  validate :student_belongs_to_course
  validate :exam_belongs_to_course
  validate :value_in_range

  scope :by_student, ->(student_id) {
    where(student_id: student_id) if student_id.present?
  }

  scope :by_grade, ->(grade_id) {
    joins(course: :grade)
    .where(grades: {id: grade_id}) if grade_id.present?
  }

  scope :by_subject, ->(subject_id) {
    joins(course: :subject)
    .where(subjects: {id: subject_id}) if subject_id.present?
  }

  def full_description
    if exam.present? && desc.empty?
      "#{exam.title} exam"
    elsif exam.present?
      "#{desc} - #{exam.title}"
    else
      desc
    end
  end

  private
  
  def student_belongs_to_course
    return if student.blank? || course.blank?

    if student.grade != course.grade
      errors.add(:course_id, "does not belong to the selected student")
    end
  end

  def exam_belongs_to_course
    return unless exam.present? || course.blank?

    if exam.course != course
      errors.add(:exam_id, "does not belong to the selected course")
    end
  end

  def value_in_range
    return unless value.present?

    unless 2 <= value && value <= 5
      errors.add(:value, "is not in range from 2 to 5")
    end
  end
end

app/models/session.rb
class Session < ApplicationRecord
  belongs_to :user
end

app/models/subject.rb
class Subject < ApplicationRecord
  has_many :courses
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :sessions, dependent: :destroy
  belongs_to :user_type

  belongs_to :grade, optional: true
  has_many :courses, foreign_key: "teacher_id", dependent: :restrict_with_exception

  has_many :marks, foreign_key: "student_id", dependent: :destroy

  validate :role_validation

  normalizes :email_address, with: ->(e) { e.strip.downcase }

  def admin?
    user_type.name == 'admin'
  end

  def teacher?
    user_type.name == 'teacher'
  end

  def student?
    user_type.name == 'student'
  end

  def gpa
    marks.average(:value).round(2) if student?
  end

  scope :by_grade, ->(grade_id) {
    where(grade_id: grade_id) if grade_id.present?
  }

  scope :by_type, ->(user_type_id) {
    where(user_type_id: user_type_id) if user_type_id.present?
  }

  private

  def role_validation
    case user_type.name
    when 'admin'
      errors.add(:grade, "Admins can't be in a grade") if grade.present?
      errors.add(:courses, "Admin can't be teaching a course") if courses.any?
      errors.add(:courses, "Admin can't be assgined a mark") if marks.any?
    when 'teacher'
      errors.add(:grade, "Teachers can't be in a grade") if grade.present?
      errors.add(:courses, "Teachers can't be assgined a mark") if marks.any?
    when 'student'
      errors.add(:courses, "Students can't be teaching a course") if courses.any?
    else
      errors.add(:user_type, "User type is invalid")
    end
  end
end

app/models/user_type.rb
class UserType < ApplicationRecord
  has_many :users
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def admin_only(&block)
    capture(&block) if Current.user&.admin?
  end

  def teacher_or_admin(&block)
    capture(&block) if Current.user&.admin? || Current.user&.teacher?
  end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/exams_helper.rb
module ExamsHelper
end

app/helpers/grades_helper.rb
module GradesHelper
end

app/helpers/marks_helper.rb
module MarksHelper
end

app/helpers/student_helper.rb
module StudentHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/teacher_helper.rb
module TeacherHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/dashboard.html.erb
<dir>
    <h1>Admin dashboard!</h1>

    <p>Welcome <%= Current.user.email_address%>!</p>

    <%= button_to "Logout", session_path, method: :delete%>

    <ul>
        <li><%= link_to "Manage users", users_path%></li>
        <li><%= link_to "Manage students", students_users_path%></li>
        <li><%= link_to "Manage grades", grades_path%></li>
        <li><%= link_to "Manage courses", courses_path%></li>
        <li><%= link_to "Manage subjects", subjects_path%></li>
        <li><%= link_to "Manage marks", marks_path%></li>
        <li><%= link_to "Manage exams", exams_path%></li>
    </ul>
</dir>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Activenow Ror" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="application-name" content="Activenow Ror">
    <meta name="mobile-web-app-capable" content="yes">
    <link rel="stylesheet" href="https://cdn.simplecss.org/simple-v1.css">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body style="max-width: 75rem">
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>