config/routes.rb
Rails.application.routes.draw do
  resources :marks
  resources :exams
  resources :courses
  resources :subjects
  resources :grades
  resource :session
  resources :users do
    collection do
      get :students
    end
  end
  resources :passwords, param: :token
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "pages#landing"
  get "dashboard", to: "pages#dashboard"

  namespace :admin do
    root "dashboard"
    resources :users
  end

  namespace :teacher do
    root "dashboard"
  end

  namespace :student do
    root "dashboard"
  end

end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :sessions, dependent: :destroy
  belongs_to :user_type

  belongs_to :grade, optional: true
  has_many :courses, foreign_key: "teacher_id", dependent: :restrict_with_exception

  has_many :marks, foreign_key: "student_id", dependent: :destroy

  validate :role_validation

  normalizes :email_address, with: ->(e) { e.strip.downcase }

  def admin?
    user_type.name == 'admin'
  end

  def teacher?
    user_type.name == 'teacher'
  end

  def student?
    user_type.name == 'student'
  end

  def gpa
    marks.average(:value).round(2) if student?
  end

  scope :by_grade, ->(grade_id) {
    where(grade_id: grade_id) if grade_id.present?
  }

  scope :by_type, ->(user_type_id) {
    where(user_type_id: user_type_id) if user_type_id.present?
  }

  private

  def role_validation
    case user_type.name
    when 'admin'
      errors.add(:grade, "Admins can't be in a grade") if grade.present?
      errors.add(:courses, "Admin can't be teaching a course") if courses.any?
      errors.add(:courses, "Admin can't be assgined a mark") if marks.any?
    when 'teacher'
      errors.add(:grade, "Teachers can't be in a grade") if grade.present?
      errors.add(:courses, "Teachers can't be assgined a mark") if marks.any?
    when 'student'
      errors.add(:courses, "Students can't be teaching a course") if courses.any?
    else
      errors.add(:user_type, "User type is invalid")
    end
  end
end

app/models/user_type.rb
class UserType < ApplicationRecord
  has_many :users
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_admin, except: [ :students ]
  before_action :require_teacher_admin, only: [ :students ]
  before_action :set_user, only: [:destroy, :edit, :update]

  def index
    @users = User.all

    @users = @users.by_grade(params[:grade_id])

    @users = @users.by_type(params[:user_type_id])
  end

  def students
    @students = User.joins(:user_type).where(user_types: { name: "student" })
    @students = @students.by_grade(params[:grade_id])
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to users_path, notice: "Account created"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to students_users_path, notice: "User was successfully updated.", status: :see_other }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @grade.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user.destroy!

    respond_to do |format|
      format.html { redirect_to users_path, notice: "User was successfully destroyed.", status: :see_other }
      format.json { head :no_content }
    end
  end
  
  private

  def user_params
    params.require(:user).permit(:email_address, :password, :password_confirmation, :user_type_id, :grade_id)
  end

  def set_user
    @user = User.find(params.expect(:id))
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<% content_for :title, "Editing user" %>

<dir>
  <h1>Editing student's grade</h1>

  <br>

  <div>
    <strong>Email:</strong>
    <%= @user.email_address %>
  </div>

  <%= form_with(model: @user) do |form| %>
  <% if @user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this subject from being saved:</h2>

      <ul>
        <% @user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :grade_id, style: "display: block" %>
    <%= form.collection_select :grade_id, Grade.all, :id, :name, prompt: "Select user type"%><br>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>


  <div>
    <%= link_to "Back to students", students_users_path %>
  </div>
</dir>

app/views/users/index.html.erb
<%= tag.div(flash[:alert], style: "color:red") if flash[:alert] %>
<%= tag.div(flash[:notice], style: "color:green") if flash[:notice] %>

<% content_for :title, "Users" %>

<dir>

    <%= link_to "Back to dashboard", admin_root_path%>

    <h1>User directory</h1>

    <%= link_to "Create user", new_user_path%>

    <%= form_with url: users_path, method: :get, local: true do %>
        <div>
            <%= label_tag :user_type_id, "Type" %>
            <%= select_tag :user_type_id,
                options_from_collection_for_select(UserType.all, :id, :name, params[:user_type_id]),
                include_blank: "Any"
            %>
        </div>

        <div>
            <%= label_tag :grade_id, "Grade" %>
            <%= select_tag :grade_id,
                options_from_collection_for_select(Grade.all, :id, :name, params[:grade_id]),
                include_blank: "Any"
            %>
        </div>

        <%= submit_tag "Filter" %>
    <% end %>

    <table id="users">
        <thead>
            <tr>
            <th>Email</th>
            <th>Type</th>
            <th></th>
            </tr>
        </thead>
        <tbody>
        <% @users.each do |user| %>
            <th><%= user.email_address %></th>
            <th><%= user.user_type.name %></th>

            <th style="text-align: center"><%= button_to "Destroy", user, method: :delete, data: { confirm: "Are you sure you want to delete this user?" } %></th>
            </tr>
        <% end %>
        </tbody>
    </table>

</dir>

app/views/users/new.html.erb
<%= tag.div(flash[:alert], style: "color:red") if flash[:alert] %>
<%= tag.div(flash[:notice], style: "color:green") if flash[:notice] %>

<%= link_to "Back to users", users_path%>

<h1>Create user</h1>

<%= form_with model: @user do |form| %>
  <%= form.email_field :email_address, required: true, autofocus: true, autocomplete: "username", placeholder: "Email address", value: params[:email_address] %><br>
  <%= form.password_field :password, required: true, autocomplete: "password", placeholder: "Password", maxlength: 72 %><br>
  <%= form.password_field :password_confirmation, required: true, placeholder: "Confirm password", maxlength: 72 %><br>
  <%= form.collection_select :user_type_id, UserType.all, :id, :name, prompt: "Select user type"%><br>
  <%= form.submit "Sign in" %>
<% end %>
<br>

app/views/users/students.html.erb
<%= tag.div(flash[:alert], style: "color:red") if flash[:alert] %>
<%= tag.div(flash[:notice], style: "color:green") if flash[:notice] %>

<% content_for :title, "Students" %>

<dir>

    <%= link_to "Back to dashboard", admin_root_path%>

    <h1>Student directory</h1>

    <%= form_with url: students_users_path, method: :get, local: true do %>

        <div>
            <%= label_tag :grade_id, "Grade" %>
            <%= select_tag :grade_id,
                options_from_collection_for_select(Grade.all, :id, :name, params[:grade_id]),
                include_blank: "Any"
            %>
        </div>

        <%= submit_tag "Filter" %>
    <% end %>

    <table id="students">
        <thead>
            <tr>
            <th>Grade</th>
            <th>Email</th>
            <th>GPA</th>
            <th></th>
            </tr>
        </thead>
        <tbody>
        <% @students.each do |student| %>
            <th><%= student.grade&.name %></th>
            <th><%= student.email_address %></th>
            <th><%= student.gpa %></th>
            <th><%= link_to "Change grade", edit_user_path(student) unless !Current.user&.admin?%></th>
            </tr>
        <% end %>
        </tbody>
    </table>

</dir>