config/routes.rb
Rails.application.routes.draw do
  resources :marks
  resources :exams
  resources :courses
  resources :subjects
  resources :grades
  resource :session
  resources :users do
    collection do
      get :students
    end
  end
  resources :passwords, param: :token
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "pages#landing"
  get "dashboard", to: "pages#dashboard"

  namespace :admin do
    root "dashboard"
    resources :users
  end

  namespace :teacher do
    root "dashboard"
  end

  namespace :student do
    root "dashboard"
  end

end

app/models/subject.rb
class Subject < ApplicationRecord
  has_many :courses
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  before_action :set_subject, only: %i[ show edit update destroy ]
  before_action :require_teacher_admin, only: %i[ index show ]
  before_action :require_admin, only: %i[ new edit create update destroy ]

  # GET /subjects or /subjects.json
  def index
    @subjects = Subject.all
  end

  # GET /subjects/1 or /subjects/1.json
  def show
  end

  # GET /subjects/new
  def new
    @subject = Subject.new
  end

  # GET /subjects/1/edit
  def edit
  end

  # POST /subjects or /subjects.json
  def create
    @subject = Subject.new(subject_params)

    respond_to do |format|
      if @subject.save
        format.html { redirect_to subjects_path, notice: "Subject was successfully created." }
        format.json { render :show, status: :created, location: @subject }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subjects/1 or /subjects/1.json
  def update
    respond_to do |format|
      if @subject.update(subject_params)
        format.html { redirect_to subjects_path, notice: "Subject was successfully updated.", status: :see_other }
        format.json { render :show, status: :ok, location: @subject }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subjects/1 or /subjects/1.json
  def destroy

    if @subject.courses.count > 0

      redirect_to subjects_path, alert: "Cannot destroy a subject with existing courses"
    
    else

      @subject.destroy!

      respond_to do |format|
        format.html { redirect_to subjects_path, notice: "Subject was successfully destroyed.", status: :see_other }
        format.json { head :no_content }
      end

    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subject
      @subject = Subject.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def subject_params
      params.expect(subject: [ :name ])
    end
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/views/subjects/_form.html.erb
<%= form_with(model: subject) do |form| %>
  <% if subject.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(subject.errors.count, "error") %> prohibited this subject from being saved:</h2>

      <ul>
        <% subject.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/subjects/_subject.html.erb
<div id="<%= dom_id subject %>">
  <div>
    <strong>Name:</strong>
    <%= subject.name %>
  </div>

</div>

app/views/subjects/edit.html.erb
<% content_for :title, "Editing subject" %>

<h1>Editing subject</h1>

<%= render "form", subject: @subject %>

<br>

<div>
  <%= link_to "Show this subject", @subject %> |
  <%= link_to "Back to subjects", subjects_path %>
</div>

app/views/subjects/index.html.erb
<%= tag.div(flash[:alert], style: "color:red") if flash[:alert] %>
<%= tag.div(flash[:notice], style: "color:green") if flash[:notice] %>

<% content_for :title, "Subjects" %>

<dir>

    <%= link_to "Back to dashboard", root_path%>

    <h1>Subject directory</h1>

    <%= admin_only do%>
      <%= link_to "Create course", new_subject_path%>
    <%end%>

    <table id="subjects">
        <thead>
            <tr>
            <th>Subject</th>
            <th>Course count</th>
            <th></th>
            </tr>
        </thead>
        <tbody>
        <% @subjects.each do |subject| %>
            <th><%= subject.name %></th>
            <th><%= subject.courses.count %></th>

            <th style="text-align: center"><%= button_to "Destroy", subject, method: :delete, data: { confirm: "Are you sure you want to delete this subject?" }, disabled: !Current.user&.admin? %></th>
            </tr>
        <% end %>
        </tbody>
    </table>

</dir>

app/views/subjects/new.html.erb
<% content_for :title, "New subject" %>

<%= link_to "Back to subjects", subjects_path%>

<h1>New subject</h1>

<%= render "form", subject: @subject %>

<br>

<div>
  <%= link_to "Back to subjects", subjects_path %>
</div>

app/views/subjects/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @subject %>

<div>
  <%= link_to "Edit this subject", edit_subject_path(@subject) %> |
  <%= link_to "Back to subjects", subjects_path %>

  <%= button_to "Destroy this subject", @subject, method: :delete %>
</div>