config/routes.rb
Rails.application.routes.draw do
  resources :marks
  resources :exams
  resources :courses
  resources :subjects
  resources :grades
  resource :session
  resources :users do
    collection do
      get :students
    end
  end
  resources :passwords, param: :token
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "pages#landing"
  get "dashboard", to: "pages#dashboard"

  namespace :admin do
    root "dashboard"
    resources :users
  end

  namespace :teacher do
    root "dashboard"
  end

  namespace :student do
    root "dashboard"
  end

end

app/models/exam.rb
class Exam < ApplicationRecord
  belongs_to :course
  has_many :marks

  scope :by_grade, ->(grade_id) {
    joins(course: :grade)
    .where(grades: {id: grade_id}) if grade_id.present?
  }

  scope :by_subject, ->(subject_id) {
    joins(course: :subject)
    .where(subjects: {id: subject_id}) if subject_id.present?
  }

  def display_name
    "#{course.display_name} - #{self.title}"
  end
end

app/controllers/exams_controller.rb
class ExamsController < ApplicationController
  before_action :require_teacher_admin
  before_action :set_exam, only: %i[ show edit update destroy ]

  # GET /exams or /exams.json
  def index
    @exams = Exam.all
    @exams = @exams.by_grade(params[:grade_id])
    @exams = @exams.by_subject(params[:subject_id])

    @grades = Grade.all
    @subjects = Subject.all

    if Current.user&.teacher?
      @exams = @exams.joins(:course).where(courses: { teacher_id: Current.user.id })
      @grades = @grades.joins(:courses).where(courses: { teacher_id: Current.user.id }).distinct
      @subjects = @subjects.joins(:courses).where(courses: { teacher_id: Current.user.id }).distinct
    end

    @past_exams = @exams.where("date < ?", Date.today)
    @exams = @exams.where("date >= ?", Date.today)
  end

  # GET /exams/1 or /exams/1.json
  def show
  end

  # GET /exams/new
  def new
    @exam = Exam.new

    @courses = Course.all

    if Current.user&.teacher?
      @courses = Course.where(teacher_id: Current.user.id)
    end
  end

  # GET /exams/1/edit
  def edit
    @courses = Course.all

    if Current.user&.teacher?
      @courses = Course.where(teacher_id: Current.user.id)
    end
  end

  # POST /exams or /exams.json
  def create
    @exam = Exam.new(exam_params)

    respond_to do |format|
      if @exam.save
        format.html { redirect_to exams_path, notice: "Exam was successfully created." }
        format.json { render :show, status: :created, location: @exam }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @exam.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /exams/1 or /exams/1.json
  def update
    respond_to do |format|
      if @exam.update(exam_params)
        format.html { redirect_to exams_path, notice: "Exam was successfully updated.", status: :see_other }
        format.json { render :show, status: :ok, location: @exam }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @exam.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /exams/1 or /exams/1.json
  def destroy
    @exam.destroy!

    respond_to do |format|
      format.html { redirect_to exams_path, notice: "Exam was successfully destroyed.", status: :see_other }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_exam
      @exam = Exam.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def exam_params
      params.expect(exam: [ :title, :date, :course_id, :grade_id, :subject_id ])
    end
end

app/helpers/exams_helper.rb
module ExamsHelper
end

app/views/exams/_exam.html.erb
<div id="<%= dom_id exam %>">
  <div>
    <strong>Title:</strong>
    <%= exam.title %>
  </div>

  <div>
    <strong>Date:</strong>
    <%= exam.date %>
  </div>

  <div>
    <strong>Course:</strong>
    <%= exam.course_id %>
  </div>

</div>

app/views/exams/_form.html.erb
<%= form_with(model: exam) do |form| %>
  <% if exam.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(exam.errors.count, "error") %> prohibited this exam from being saved:</h2>

      <ul>
        <% exam.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :date, style: "display: block" %>
    <%= form.date_field :date %>
  </div>

  <div>
    <%= form.label :course_id, style: "display: block" %>
    <%= form.text_field :course_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/exams/edit.html.erb
<%= tag.div(flash[:alert], style: "color:red") if flash[:alert] %>
<%= tag.div(flash[:notice], style: "color:green") if flash[:notice] %>

<% content_for :title, "Edit exam" %>

<div>
  <div>
    <%= link_to "Back to exams", exams_path %>
  </div>

  <h1>New exam</h1>

  <%= form_with model: @exam do |form| %>
    <% if @exam.errors.any? %>
    <div id="error_explanation" style="color: red;">
      <h2><%= pluralize(@exam.errors.count, "error") %> prevented this exam from being saved:</h2>
      <ul>
        <% @exam.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

    <div class='field'>Course:</div>
    <div class='field'><%= form.collection_select :course_id, @courses, :id, :display_name, prompt: "Select course", required: true%></div>
    <div class='field'>Title:</div>
    <div class='field'><%= form.text_field :title, placeholder: "Exam title", required: true %></div>
    <div class='field'>Date:</div>
    <div class='field'><%= form.date_field :date, min: Date.today, required: true %></div>
    <div class='actions'><%= form.submit "Add mark" %></div>
  <% end %>
</div>

app/views/exams/index.html.erb
<%= tag.div(flash[:alert], style: "color:red") if flash[:alert] %>
<%= tag.div(flash[:notice], style: "color:green") if flash[:notice] %>

<% content_for :title, "Exams" %>

<dir>

    <%= link_to "Back to dashboard", root_path%>

    <h1>Exams directory</h1>

    <%= link_to "Create exam", new_exam_path%>

    <%= form_with url: exams_path, method: :get, local: true do %>
        <div>
            <%= label_tag :grade_id, "Grade" %>
            <%= select_tag :grade_id,
                options_from_collection_for_select(@grades, :id, :name, params[:grade_id]),
                include_blank: "Any"
            %>
        </div>

        <div>
            <%= label_tag :subject_id, "Subject" %>
            <%= select_tag :subject_id,
                options_from_collection_for_select(@subjects, :id, :name, params[:subject_id]),
                include_blank: "Any"
            %>
        </div>
        <%= submit_tag "Filter" %>
    <% end %>

    <h2>Upcoming exams</h2>

    <table id="exams">
        <thead>
            <tr>
            <th>Date</th>
            <th>Title</th>
            <th>Grade</th>
            <th>Subject</th>
            <th></th>
            <th></th>
            </tr>
        </thead>
        <tbody>
        <% @exams.each do |exam| %>
            <th><%= exam.date %></th>
            <th><%= exam.title %></th>
            <th><%= exam.course.grade.name %></th>
            <th><%= exam.course.subject.name %></th>
            <th style="text-align: center"><%= link_to "Edit", edit_exam_path(exam) %></th>
            <th style="text-align: center"><%= button_to "Destroy", exam, method: :delete, data: { confirm: "Are you sure you want to delete this exam?" } %></th>
            </tr>
        <% end %>
        </tbody>
    </table>

    <h2>Past exams</h2>

    <table id="past_exams">
        <thead>
            <tr>
            <th>Date</th>
            <th>Title</th>
            <th>Grade</th>
            <th>Subject</th>
            <th>Attendance</th>
            </tr>
        </thead>
        <tbody>
        <% @past_exams.each do |exam| %>
            <th><%= exam.date %></th>
            <th><%= exam.title %></th>
            <th><%= exam.course.grade.name %></th>
            <th><%= exam.course.subject.name %></th>
            <th><%= exam.marks.count %></th>
            </tr>
        <% end %>
        </tbody>
    </table>

</dir>

app/views/exams/new.html.erb
<%= tag.div(flash[:alert], style: "color:red") if flash[:alert] %>
<%= tag.div(flash[:notice], style: "color:green") if flash[:notice] %>

<% content_for :title, "New exam" %>

<div>
  <div>
    <%= link_to "Back to exams", exams_path %>
  </div>

  <h1>New exam</h1>

  <%= form_with model: @exam do |form| %>
    <% if @exam.errors.any? %>
    <div id="error_explanation" style="color: red;">
      <h2><%= pluralize(@exam.errors.count, "error") %> prevented this exam from being saved:</h2>
      <ul>
        <% @exam.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

    <div class='field'><%= form.collection_select :course_id, @courses, :id, :display_name, prompt: "Select course", required: true%></div>
    <div class='field'><%= form.text_field :title, placeholder: "Exam title", required: true %></div>
    <div class='field'><%= form.date_field :date, min: Date.today, required: true %></div>
    <div class='actions'><%= form.submit "Add mark" %></div>
  <% end %>
</div>

app/views/exams/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @exam %>

<div>
  <%= link_to "Edit this exam", edit_exam_path(@exam) %> |
  <%= link_to "Back to exams", exams_path %>

  <%= button_to "Destroy this exam", @exam, method: :delete %>
</div>